### ISSUE TITLE
Alt+X or rebuild command causes "Show class equipment" option to bug out

### ISSUE THREAD

**Issue by trihardseven** [BarleyFlour/WrathVisualAdjustmentsMod#103]
Basically whenever you have show class equipment turned on and use the rebuild command the character reverts back to showing their current equipment rather than class equipment. Since the grey hair bug is very common for me this is pretty annoying, my character's equipment makes him look like a clown...

**Comment by BarleyFlour** [comment]
Could you send me your Player.log file?

**Comment by Duskwood0585** [comment]
I've been having a similar issue where the armor I've selected in overrides doesn't appear randomly after zoning or rebuilding character, and no matter what I put on, I'm just in my default gear.

**Comment by trihardseven** [comment]
Found a workaround by removing their armor using the mod instead of the game Show class equipment option
