### ISSUE TITLE
Save Dependency gone but not really.

### ISSUE THREAD

**Issue by Duskwood0585** [BarleyFlour/WrathVisualAdjustmentsMod#114]
The new version did make it load up after uninstalling the mod, but still running into the issue of hide helmet / backpack not working and instead turning my char grey / hair gold (as an aasmir with white hair).

**Comment by rayban87** [comment]
Save dependency not gone.
I have the latest version installed via unity and I loaded my save, turned off this mod and then made a new save.
Switched off my game, uninstalled the mod via unity, tried to load my save and it keeps cutting back to the main menu.
I have to install the mod again and activate it again to be able to load my save again.
