### ISSUE TITLE
"Unlock hair" not functioning

### ISSUE THREAD

**Issue by SeveralGeese** [BarleyFlour/WrathVisualAdjustmentsMod#122]
Updating from previous version. Option to unlock all hair models does nothing when ticked on. 
Tested with both the visual adjustment menu and in character respec. 

Playing as a female tiefling female in act 2, though I doubt that would affect it.

(seems like a lot of other features are being glitchy or nonfunctional too.)

**Comment by BarleyFlour** [comment]
Have you updated your mod and game?

**Comment by SeveralGeese** [comment]
Yep. The game updated automatically, and the mod completely stopped working.  So I installed the most recent update for that and got it *mostly* working, but with all these issues. 
Maybe I messed up with uninstalling the previous version?

**Comment by BarleyFlour** [comment]
that being 1.13.2 or greater?

**Comment by SeveralGeese** [comment]
Aha! I must have updated to 1.13.2 moments before you released 1.13.3
updated just now, that seems to have fixed the side stuff that was glitchy and nonfunctional, but I still only have access to the 9 hair options that are normally available to Tieflings, even with "unlock hair" ticked on. 

related to that new Free-LC , maybe?
