### ISSUE TITLE
Can't remove the gray skin of Mythic Lich

### ISSUE THREAD

**Issue by ElenaroArmero** [BarleyFlour/WrathVisualAdjustmentsMod#125]
The gray skin of the lich is not removed in any way, even when choosing a visual of another mythic.
Correction: gray skin remains only in the inventory window, everything works fine with the model on the map.

**Comment by ElenaroArmero** [comment]
Correction: gray skin remains only in the inventory window, everything works fine with the model on the map.

**Comment by VladCastle** [comment]
Are you sure you are not grey from being first step lich (before being skeleton)?
One (a glitch) is with clothes becoming brownish, the other (mythic path) without changes to clothes.

**Comment by ElenaroArmero** [comment]
Yes, my character is in the path of the lich, and therefore it is gray. And I was just trying to remove it. Am I doing something wrong?

**Comment by BarleyFlour** [comment]
Fixed with v1.13.5
