### ISSUE TITLE
Mythic appearance options

### ISSUE THREAD

**Issue by Mev1012** [BarleyFlour/WrathVisualAdjustmentsMod#13]
not sure how practical this is but could you make an option to make mythic heroes look normal cause tomato demon isn't cool.

**Comment by BarleyFlour** [comment]
If you could shoot over a save so i can test then i can give it a look.

**Comment by Mev1012** [comment]
> If you could shoot over a save so i can test then i can give it a look.

how? sorry I only made a github to use your mod

**Comment by Codetalker1988** [comment]
[Manual_5______12______IX__4715__08_11_22.zip](https://github.com/BarleyFlour/WrathVisualAdjustmentsMod/files/7113489/Manual_5______12______IX__4715__08_11_22.zip)

I have a save here, it's just before choose the paths,but not contain the higher 3 paths.

**Comment by BarleyFlour** [comment]
Added with 1.09.0
