### ISSUE TITLE
Regarding future updates:

### ISSUE THREAD

**Issue by BarleyFlour** [BarleyFlour/WrathVisualAdjustmentsMod#137]
Due to my dad passing away from cancer recently updates and bugfixes might be slow and infrequent.
As I'm finding it hard to have any motivation to do anything.

**Comment by nokturnihs** [comment]
I'm so incredibly sorry for your loss! That's gotta be one of the hardest things to deal with - my dad is my best friend and my world would be shattered if he passed away! Mourn. Grieve. Heal. So sorry you're going through rough times!
