### ISSUE TITLE
After reload the companions' doll always reset

### ISSUE THREAD

**Issue by Adromolek** [BarleyFlour/WrathVisualAdjustmentsMod#3]
For example, I use this mod to set Lane's doll to human, set his face to type 3, hair to 6, and hair color to 6, but after I reload the game, it will be reset to human, face 0, hair 0, and hair color 0

Besides, hide item cloak also doesn't work well.

**Comment by BarleyFlour** [comment]
Does this happen with all companions or only Lann?

**Comment by Adromolek** [comment]
> Does this happen with all companions or only Lann?

  emmmmmmm，I just realized that this bug only happened in Chapter 1 but in all companions. if you used destroy doll and create doll, it will be reset to face 0, hair 0, and hair color 0, but if you just changed the doll, it will be reset to the doll you created at the beginning

**Comment by BarleyFlour** [comment]
Should be fixed with 1.03.0 but unsure as it was hard for me to recreate.
