### ISSUE TITLE
Specific Equipment colour

### ISSUE THREAD

**Issue by ooblagis** [BarleyFlour/WrathVisualAdjustmentsMod#30]
Lots of equipment now pull their own colour data, and a lot of the equipment options look pretty bland without that colour. The option to override the colour on specific equipment slots would be appreciated. 

Plus, the Character info is already displaying the equipment colour info, so I imagine it wouldn't be TOO difficult to then add the override component.

**Comment by MaelcumZion** [comment]
This would be a great feature. good idea.

**Comment by AshodinVenteal** [comment]
Being able to dye your equipment would be really cool, and make Pathfinder into Pathfinder: Fashion of the Righteous!

**Comment by BarleyFlour** [comment]
Added with v1.10.0
