### ISSUE TITLE
Mod doesnt show up.

### ISSUE THREAD

**Issue by liilAmy** [BarleyFlour/WrathVisualAdjustmentsMod#32]
I followed the directions, but when I ctr-f10, the mod screen is emtpy, the mod is not there.

**Comment by BarleyFlour** [comment]
Are you sure that you pointed UMM to the correct folder and that you downloaded the proper .zip, that being "VisualAdjustments.zip" not "Source Code.zip"

**Comment by liilAmy** [comment]
sooooo um.... I have no idea how but it ended up in my starbound mod folder
instead of my WotR mod folder O.o
