### ISSUE TITLE
Request for saucy party/succubus garb as option for class clothing

### ISSUE THREAD

**Issue by Hero4Rent** [BarleyFlour/WrathVisualAdjustmentsMod#40]
Just a silly request, but when rescuing the Aasimar in the party/or dealing with a certain style of foe, they all have pretty stylish undergarb that looks way better than the default brown shorts and/or chestwrap.  No idea if it's a global model for all races or just the few presented, but it'd be a fanastic base for the old Borris era pinup art style looks, for gents and ladies alike.

Even better if it or the default wrap could be customized, color wise.

**Comment by woshifang777** [comment]
strong support！！

**Comment by angryowlbear** [comment]
Please add some alternative underwear for male aswell if possible, I'm trying to emulate a custom portrait that is more of a Conan-style "naked" barbarian, his undergarb is somewhat like a metallic speedo (think old school superheroes, but metal) If possible would be much appreciated.

**Comment by typoking7** [comment]
Thirded

**Comment by BarleyFlour** [comment]
Regrettably added with v1.10.0, keep it in your pants :/
