### ISSUE TITLE
When change outfit, body type and hair reload and are never saved

### ISSUE THREAD

**Issue by vnth7** [BarleyFlour/WrathVisualAdjustmentsMod#49]
Hair and body type become default and bald if you change outfit. This occurs every time you open the game.

**Comment by angryowlbear** [comment]
Same problem. Extremely annoying!!!

**Comment by Dark0Zero** [comment]
I've got a similar problem.

Female character, haven't tried male yet, upon changing class outfit the body type defaults to the base and refuses to save.

**Comment by BarleyFlour** [comment]
Fixed with v1.10.0
