### ISSUE TITLE
How to color armors

### ISSUE THREAD

**Issue by Serapheil** [BarleyFlour/WrathVisualAdjustmentsMod#51]
Maybe I am just an idiot, maybe there's a bug, maybe it simply isn't an intended feature, but I CANNOT for the life of me figure out how to color the actual armors. Changing outfit colors works fine and properly changes the underlying outfit, but is there no way to make it so whatever armor override you choose isn't just some variation of a flat grey? I would like armors and accessories that aren't grey.

**Comment by BarleyFlour** [comment]
Being worked on.

**Comment by BarleyFlour** [comment]
Added with v1.10.0
