### ISSUE TITLE
My tiefling goes bald

### ISSUE THREAD

**Issue by RevanStarforge** [BarleyFlour/WrathVisualAdjustmentsMod#53]
My tiefling's [male model, if it helps] hair is resetted to a certain color and baldness whenever i RESTART the game itself.

It's fine when i play a bit, reload to save, or even another save. But if i exit the game, restart and open my save, i'm bald again...

Edit: Also i did something as well. I changed my character doll complately. I made my tiefling a half elf. It worked, like it works in Kingmaker... I saved, i reloaded, a played a bit all fine.

BUT, when i saved the game... EXIT the game... Restart and reload the save, i'm tiefling again with no hair... So... Is it a bug, or am i doing something horribly wrong?

**Comment by BarleyFlour** [comment]
Fixed with v1.10.0
