### ISSUE TITLE
Baldness/Settings not sticking Returns

### ISSUE THREAD

**Issue by RevanStarforge** [BarleyFlour/WrathVisualAdjustmentsMod#55]
After couple restarts/save loads ect, my tiefling still refuses to remain to look like an half elf... and still bald

**Comment by BarleyFlour** [comment]
Should be fixed with v1.10.1 but as i cant recreate im not sure.

**Comment by RevanStarforge** [comment]
i don't know if i broke something irreverseably with my save either... i use your mod since day 1 of the game's official release...
