### ISSUE TITLE
Regarding Updating Equipment and Colors

### ISSUE THREAD

**Issue by Ner013** [BarleyFlour/WrathVisualAdjustmentsMod#60]
I am really thankful for all your hard work, my party looks great thanks to the equipment appearance swapping, and I know they'll look even better with the new color picker!

However there are some issues. The first problem is that I in my testing of the new EE picker, for armors (and maybe others) the secondary colors synch up with the primary colors on load (ex. I set primary to red, and secondary to white, but when I load the game the armor is red because both colors have been set to red). Unedited armors on load return to grey, but once unequipped and reequipped they regain color. 

The second issue is swapping the equipment once the colors have been set. When I tried to swap armor sets, the character still had the previous armor model equipped. (ex. I swapped a padded armor with a color installed with a leather armor, the inventory sheet updated the armor but the character model was still wearing the color padded armor. Another example is when I colored a cloak but tried to unequipped it the slot was empty but the model was still wearing the cloak. Clicking reset will undo any changes and allows the character to wear new equipment as according to the inventory sheet)

I'm not sure if the second one is a bug or if that's how the EE picker works, but either way I look forward to the next update and what other mods you have in mind!

**Comment by Serapheil** [comment]
For the second issue, you can just remove the part that's sticking in EE and search for/re-apply it later if you want it again. The colors syncing up is definitely a common problem I have as well though.

**Comment by BarleyFlour** [comment]
The first one is a bug, the second is just how the EE Picker works, and the first one is fixed with v1.10.3

**Comment by Ner013** [comment]
Thank you for the quick fix, sorry about bugging you about the second issue, all of these great customization options are a bit overwhelming since the first visual adjustments in Kingmaker was just sliders. Looking forward what else you have in mind for the future!
