### ISSUE TITLE
Back Items on Half-Orc character with EES flipping around when walking.

### ISSUE THREAD

**Issue by typoking7** [BarleyFlour/WrathVisualAdjustmentsMod#63]
Not _entirely_ sure if this is a problem with the mod or with the game itself, but because I can't load up the affected save file without the mod due to using EES on my main character, I'm going to mention it here.

Here's a picture of the issue:
![bug](https://user-images.githubusercontent.com/90056736/133956154-d34cef9a-841e-4fa3-b093-e7a5a82cdb90.png)

I can't seem to get the problem to appear on my non half-orc character, but I'm not sure if that's because I didn't use EES with him or if it's because he's not a half-orc.

**Comment by nehm-ow** [comment]
This may just be a base game problem.  I have the same issue and I haven't been running any mods.

**Comment by typoking7** [comment]
I had a suspicion that might be the case.
