### ISSUE TITLE
upgrade to v1.10.4 broke the mod

### ISSUE THREAD

**Issue by cnieuweboer** [BarleyFlour/WrathVisualAdjustmentsMod#67]
Version v1.10.4 broke outfit, overrides and select equipment. 

After upgrade characters all load in with their default armor. Outfit menu is completely empty. The mod's menu options for armor overrides are set to "none" and can't be changed. Select equipment works for characters with the default look like MC of mercenaries, but doesn't work for most companions.

I tried disabling other mods I was using, but makes not difference. Going back to v1.10.3 fixed things.

**Comment by Firstrolls** [comment]
Same issue for me, reverted back to 1.10.3

**Comment by BarleyFlour** [comment]
fixed with v1.10.5
