### ISSUE TITLE
Equipped Weapons getting "Stuck."

### ISSUE THREAD

**Issue by typoking7** [BarleyFlour/WrathVisualAdjustmentsMod#7]
I have this odd problem where the appearance of a weapon gets "stuck" on my characters. Say I equip a longsword and then unequip it. Even though my character makes the unarmed weapon stance, he's still holding a longsword. The only way to fix this that I've seen is to press the debug reload button, but once I restart the game the problem's back.

Here's an image of what it looks like.
![bugged](https://user-images.githubusercontent.com/90056736/132033880-22744f3d-532a-4481-80cb-c66ce16f4030.png)

**Comment by Cybersouls** [comment]
Similar issue here, yeah. No idea what it's about.
