### ISSUE TITLE
Bald Heads

### ISSUE THREAD

**Issue by IdiotEm** [BarleyFlour/WrathVisualAdjustmentsMod#9]
Upon loading in, characters appear bald, pale, or in the wrong outfit. Most often occurs after messing with override settings.

**Comment by AshodinVenteal** [comment]
I also get this bug = it started for me in 1.08 and 1.09, 1.07 was fine. 

Hair Style = 53
Unlock Hair = Checked
Race = Half-Elf Male
Custom Hair Color = Checked
Show Hair Color Picker = Checked

Hair RGB Value = 35, 38, 49

Hide Helmet = Checked
Hide Cloak = Checked
Hide Sheaths/Scabbards = Checked

**Comment by BarleyFlour** [comment]
Fixed with v1.10.2
